server:
  port: 7002

mp.lra:
  coordinator.url: http://otmm-tcs:9000/api/v1/lra-coordinator
  #coordinator.url: http://lra-coordinator:8080/lra-coordinator
  propagation.active: true
  #participant.url: http://host.docker.internal:7002
  participant.url: http://f1-payment-service:7002